/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTodosRouteImport } from './routes/api/todos'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppProtectedRouteRouteImport } from './routes/_app/_protected/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppProtectedTodosRouteImport } from './routes/_app/_protected/todos'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProtectedRouteRoute = AppProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProtectedTodosRoute = AppProtectedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AppProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AppLoginRoute
  '/api/todos': typeof ApiTodosRoute
  '/todos': typeof AppProtectedTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AppLoginRoute
  '/api/todos': typeof ApiTodosRoute
  '/todos': typeof AppProtectedTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/_protected': typeof AppProtectedRouteRouteWithChildren
  '/_app/login': typeof AppLoginRoute
  '/api/todos': typeof ApiTodosRoute
  '/_app/_protected/todos': typeof AppProtectedTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/api/todos' | '/todos' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/todos' | '/todos' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_protected'
    | '/_app/login'
    | '/api/todos'
    | '/_app/_protected/todos'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiTodosRoute: typeof ApiTodosRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_protected': {
      id: '/_app/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppProtectedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_protected/todos': {
      id: '/_app/_protected/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AppProtectedTodosRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
  }
}

interface AppProtectedRouteRouteChildren {
  AppProtectedTodosRoute: typeof AppProtectedTodosRoute
}

const AppProtectedRouteRouteChildren: AppProtectedRouteRouteChildren = {
  AppProtectedTodosRoute: AppProtectedTodosRoute,
}

const AppProtectedRouteRouteWithChildren =
  AppProtectedRouteRoute._addFileChildren(AppProtectedRouteRouteChildren)

interface AppRouteRouteChildren {
  AppProtectedRouteRoute: typeof AppProtectedRouteRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProtectedRouteRoute: AppProtectedRouteRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiTodosRoute: ApiTodosRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './index.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
